# Generated by Django 4.2.29 on 2026-04-03 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('services', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datetime_start', models.DateTimeField(verbose_name='Начало')),
                ('datetime_end', models.DateTimeField(verbose_name='Конец')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждена'), ('completed', 'Завершена'), ('cancelled_by_client', 'Отменена клиентом'), ('cancelled_by_admin', 'Отменена администратором'), ('no_show', 'Не явился')], default='pending', max_length=30, verbose_name='Статус')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая цена')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Напоминание отправлено')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clients.client', verbose_name='Клиент')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='staff.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-datetime_start'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_at_booking', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена на момент записи')),
                ('duration_at_booking', models.PositiveIntegerField(verbose_name='Длительность на момент записи')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='appointments.appointment', verbose_name='Запись')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга в записи',
                'verbose_name_plural': 'Услуги в записях',
            },
        ),
    ]
