# Generated by Django 4.2.29 on 2026-04-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('promo', 'Акция'), ('certificate', 'Сертификат')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
