# Generated by Django 4.2.29 on 2026-04-03 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='masters/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('working_hours', models.JSONField(default=dict, verbose_name='Рабочие часы')),
                ('break_slots', models.JSONField(default=list, verbose_name='Перерывы')),
                ('vacations', models.JSONField(default=list, verbose_name='Отпуска')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='MasterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Кастомная цена')),
                ('custom_duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кастомная длительность')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включена')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_services', to='staff.master', verbose_name='Мастер')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_services', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга мастера',
                'verbose_name_plural': 'Услуги мастеров',
                'unique_together': {('master', 'service')},
            },
        ),
    ]
