# Generated by Django 4.2.29 on 2026-04-04 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='working_hours',
            field=models.JSONField(default=dict, verbose_name='Рабочие часы (по дням недели)'),
        ),
        migrations.CreateModel(
            name='MasterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.CharField(max_length=5, verbose_name='Начало')),
                ('end_time', models.CharField(max_length=5, verbose_name='Конец')),
                ('is_working', models.BooleanField(default=True, verbose_name='Рабочий день')),
                ('breaks', models.JSONField(blank=True, default=list, verbose_name='Перерывы')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='staff.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Расписание мастера',
                'verbose_name_plural': 'Расписания мастеров',
                'ordering': ['date'],
                'unique_together': {('master', 'date')},
            },
        ),
    ]
