# Generated by Django 4.2.29 on 2026-04-04 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_master_working_hours_masterschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_edit_schedule', models.BooleanField(default=False, verbose_name='Может редактировать график')),
                ('can_reply_reviews', models.BooleanField(default=False, verbose_name='Может отвечать на отзывы')),
                ('master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='staff.master', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Разрешения мастера',
                'verbose_name_plural': 'Разрешения мастеров',
            },
        ),
    ]
