# Generated by Django 4.2.29 on 2026-04-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_masterpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='_cached_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Кэшированный рейтинг'),
        ),
    ]
