import api from './client'

export const getCategories = () => api.get('/services/service-categories/')
export const getServices = (params?: Record<string, string>) => api.get('/services/services/', { params })
export const getService = (slug: string) => api.get(`/services/services/${slug}/`)
export const createService = (data: Record<string, unknown>) => api.post('/admin-panel/services/', data)
export const updateService = (id: number, data: Record<string, unknown>) => api.patch(`/admin-panel/services/${id}/`, data)
export const deleteService = (id: number) => api.delete(`/admin-panel/services/${id}/`)
export const getMasters = (params?: Record<string, string>) => api.get('/staff/masters/', { params })
export const getMaster = (id: number) => api.get(`/staff/masters/${id}/`)
export const getMasterSlots = (masterId: number, date: string, serviceIds: number[]) =>
  api.get('/appointments/appointments/available_slots/', { params: { master_id: masterId, date, service_ids: serviceIds.join(',') } })
export const getAvailableMasters = (serviceId: number, date: string) =>
  api.get('/staff/masters/available-masters/', { params: { service_id: serviceId, date } })
export const getPromotions = () => api.get('/promotions/promotions/')
export const getReviews = (params?: Record<string, string>) => api.get('/reviews/reviews/', { params })
export const createReview = (data: Record<string, unknown>) => api.post('/reviews/reviews/', data)
export const createGuestAppointment = (data: Record<string, unknown>) => api.post('/appointments/guest/', data)
export const createAppointment = (data: Record<string, unknown>) => api.post('/appointments/appointments/', data)
export const getMyAppointments = (params?: Record<string, string>) => api.get('/appointments/appointments/', { params })
export const cancelAppointment = (id: number) => api.post(`/appointments/appointments/${id}/cancel/`)
export const repeatAppointment = (id: number) => api.post(`/appointments/appointments/${id}/repeat/`)
export const getProfile = () => api.get('/clients/profile/')
export const getFavorites = () => api.get('/clients/favorites/')
export const addFavorite = (masterId: number) => api.post('/clients/favorites/', { master: masterId })
export const removeFavorite = (id: number) => api.delete(`/clients/favorites/${id}/`)
export const sendSmsCode = (phone: string) => api.post('/auth/sms/send/', { phone })
export const verifySmsCode = (phone: string, sms_code: string) => api.post('/auth/sms/verify/', { phone, sms_code })
export const loginApi = (phone: string, password: string) => api.post('/auth/login/', { phone, password })
export const registerUser = (data: Record<string, unknown>) => api.post('/auth/register/', data)
export const getDashboardStats = (params?: Record<string, string>) => api.get('/admin-panel/dashboard/stats/', { params })
export const getAdminCalendar = (params: Record<string, string>) => api.get('/admin-panel/calendar/', { params })
export const getAdminMasters = () => api.get('/admin-panel/masters/')
export const createAdminMaster = (data: Record<string, unknown>) => api.post('/admin-panel/masters/', data)
export const updateAdminMaster = (id: number, data: Record<string, unknown>) => api.put(`/admin-panel/masters/${id}/`, data)
export const deleteAdminMaster = (id: number) => api.delete(`/admin-panel/masters/${id}/`)
export const getAdminAppointments = (params?: Record<string, string>) => api.get('/admin-panel/appointments/', { params })
export const updateAppointmentStatus = (id: number, status: string) => api.patch(`/admin-panel/appointments/${id}/`, { status })
export const createAdminAppointment = (data: Record<string, unknown>) => api.post('/admin-panel/appointments/', data)
export const getSalesReport = (params: Record<string, string>) => api.get('/admin-panel/reports/sales/', { params, responseType: 'blob' })
export const sendSmsBroadcast = (data: Record<string, unknown>) => api.post('/admin-panel/sms-broadcast/', data)
export const getBlacklist = () => api.get('/promotions/blacklist/')
export const addToBlacklist = (data: Record<string, unknown>) => api.post('/promotions/blacklist/', data)
export const removeFromBlacklist = (id: number) => api.delete(`/promotions/blacklist/${id}/`)
