# Generated by Django 4.2.29 on 2026-04-03 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='Код')),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Номинал')),
                ('buyer_name', models.CharField(max_length=200, verbose_name='Имя покупателя')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email получателя')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата использования')),
            ],
            options={
                'verbose_name': 'Подарочный сертификат',
                'verbose_name_plural': 'Подарочные сертификаты',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Ключ')),
                ('value', models.TextField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Скидка (%)')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Промокод')),
                ('applicable_services', models.ManyToManyField(blank=True, to='services.service', verbose_name='Применимые услуги')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BlacklistedClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(verbose_name='Причина')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_entry', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Чёрный список',
                'verbose_name_plural': 'Чёрный список',
            },
        ),
    ]
