# Generated by Django 4.2.29 on 2026-04-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалён'),
        ),
        migrations.AddField(
            model_name='review',
            name='master_reply',
            field=models.TextField(blank=True, default='', verbose_name='Ответ мастера'),
        ),
    ]
